[program:toolsandbox-qwen]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/toolsandbox-qwen.sh
autostart=true
autorestart=unexpected
startsecs=10
startretries=2
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_events_enabled=true
stdout_logfile_maxbytes=0
