[program:toolsandbox-calibration]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/toolsandbox-calibration.sh
autostart=false
autorestart=false
startsecs=1
startretries=0
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_events_enabled=true
stdout_logfile_maxbytes=0
